package cmd

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"time"

	"github.com/GrayCodeAI/rho/internal/autoinit"
	"github.com/GrayCodeAI/rho/internal/intelligence/repomap"
)

// autoInitContextFile is the project-level context file the auto-init runner
// writes when it generates a starter summary. AGENTS.md is one of the context
// files autoinit.HasContext recognizes, so once written the gating will never
// fire again for this project.
const autoInitContextFile = "AGENTS.md"

// maybeAutoInit kicks off the one-time, gated auto-init pass for the current
// project. It is intentionally additive and safe-by-default:
//
//   - It runs in a background goroutine so it never blocks chat startup.
//   - It is a no-op unless the project has NO context file (AGENTS.md / RHO.md
//     / CONTEXT.md), no auto-init marker exists yet, and the
//     RHO_DISABLE_AUTO_INIT kill switch is unset — all enforced by
//     autoinit.MaybeRun.
//   - Any failure (analysis error, write error) is swallowed; startup proceeds.
//
// Wiring this changes nothing for existing projects (they already have a
// context file or will after the first attempt), and the kill switch fully
// opts out.
func maybeAutoInit(ctx context.Context) {
	root, err := os.Getwd()
	if err != nil || root == "" {
		return
	}
	go func() {
		// MaybeRun handles all gating (disable env, marker, existing context).
		if _, err := autoinit.MaybeRun(ctx, autoinit.Options{
			Root: root,
			Run:  autoInitRunner,
		}); err != nil {
			slog.Warn("auto-init failed", "root", root, "error", err)
		}
	}()
}

// autoInitRunner drives the existing codebase-analysis machinery (the same
// hierarchical repomap summary that powers init/repomap) and writes a starter
// AGENTS.md context file for the project. It mirrors the intent of the
// init-deep skill / `rho init` without coupling to the agentic flow: a cheap,
// deterministic, dependency-free pass that gives the project a baseline context
// file. The function is only ever invoked by autoinit.MaybeRun, which has
// already confirmed the project has no context file.
func autoInitRunner(ctx context.Context, root string) error {
	// Bound the analysis so a huge repo cannot stall the background pass.
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	type result struct {
		summary string
		err     error
	}
	done := make(chan result, 1)
	go func() {
		h, err := repomap.BuildHierarchy(root)
		if err != nil {
			done <- result{err: err}
			return
		}
		done <- result{summary: h.FormatLevel1(2000)}
	}()

	var summary string
	select {
	case <-ctx.Done():
		return ctx.Err()
	case r := <-done:
		if r.err != nil {
			return r.err
		}
		summary = r.summary
	}

	out := filepath.Join(root, autoInitContextFile)
	// Never clobber an existing file (defensive: gating should already prevent
	// this, but a context file could have appeared between the check and now).
	if _, err := os.Stat(out); err == nil {
		return nil
	}

	content := autoInitContextContent(filepath.Base(root), summary)
	// #nosec G306 -- starter context file is a project doc intended to be committed and normally readable
	return os.WriteFile(out, []byte(content), 0o644)
}

// autoInitContextContent renders the starter context file body.
func autoInitContextContent(projectName, summary string) string {
	if summary == "" {
		summary = "(no Go packages detected)\n"
	}
	return fmt.Sprintf(`# %s

> Auto-generated by rho on first run. Edit freely or delete to regenerate.
> Set RHO_DISABLE_AUTO_INIT=1 to opt out of automatic context generation.

## Package map

%s
`, projectName, summary)
}
