package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	rhoconfig "github.com/GrayCodeAI/rho/internal/config"
	"github.com/GrayCodeAI/rho/internal/plugin"
	"github.com/GrayCodeAI/rho/internal/provider/routing"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// FlagInfo describes a CLI flag for completion generation.
type FlagInfo struct {
	Name        string   `json:"name"`
	Short       string   `json:"short,omitempty"`
	Description string   `json:"description"`
	Type        string   `json:"type"` // "string", "bool", "int"
	Choices     []string `json:"choices,omitempty"`
}

// CommandInfo describes a CLI command for completion generation.
type CommandInfo struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Subcommands []CommandInfo `json:"subcommands,omitempty"`
	Flags       []FlagInfo    `json:"flags,omitempty"`
}

// CompletionGenerator generates shell completion scripts for rho.
type CompletionGenerator struct {
	Commands      []CommandInfo `json:"commands"`
	Flags         []FlagInfo    `json:"flags"`
	SlashCommands []string      `json:"slash_commands"`
	Models        []string      `json:"models"`
	Providers     []string      `json:"providers"`
}

// NewCompletionGenerator creates a CompletionGenerator pre-populated with rho's
// command structure, flags, providers, models, and slash commands.
func NewCompletionGenerator() *CompletionGenerator {
	g := &CompletionGenerator{}
	g.populateCommands()
	g.populateFlags()
	g.populateProviders()
	g.populateModels()
	g.populateSlashCommands()
	return g
}

func (g *CompletionGenerator) populateCommands() {
	g.Commands = commandInfosFromCobra(rootCmd.Commands())
	augmentCommandInfos(g.Commands)
}

func (g *CompletionGenerator) populateFlags() {
	g.Flags = flagsFromFlagSet(rootCmd.Flags())
}

func (g *CompletionGenerator) populateProviders() {
	g.Providers = rhoconfig.AllSetupGateways()
}

func (g *CompletionGenerator) populateModels() {
	g.Models = routing.AllCatalogModelNames()
}

func (g *CompletionGenerator) populateSlashCommands() {
	// Keep shell, JSON, and interactive completion on the same catalog used by
	// dispatch, the command palette, and in-chat suggestions. A second literal
	// list silently drifted whenever a command was added or migrated.
	runtime := plugin.NewRuntime()
	if err := runtime.LoadAll(); err == nil {
		// Loading manifests is read-only; plugin scripts are not executed. This
		// keeps generated shell completion aware of installed plugin commands.
		g.SlashCommands = slashCommandsFor(runtime)
		return
	}
	// Completion must remain available when a plugin manifest is malformed or
	// unreadable. Static rho commands are still a complete fallback.
	g.SlashCommands = slashCommands()
}

// GenerateBash returns a complete bash completion script for rho.
func (g *CompletionGenerator) GenerateBash() string {
	var b strings.Builder

	b.WriteString("# bash completion for rho\n")
	b.WriteString("# Auto-generated by rho completions generator\n\n")

	// Build subcommand list
	subcommands := make([]string, 0, len(g.Commands))
	for _, cmd := range g.Commands {
		subcommands = append(subcommands, cmd.Name)
	}

	// Build flag list
	flags := make([]string, 0, len(g.Flags))
	for _, f := range g.Flags {
		flags = append(flags, "--"+f.Name)
		if f.Short != "" {
			flags = append(flags, "-"+f.Short)
		}
	}

	// Build provider list
	providers := strings.Join(g.Providers, " ")

	// Build slash commands list
	slashCmds := strings.Join(g.SlashCommands, " ")

	b.WriteString("_rho_completions() {\n")
	b.WriteString("    local cur prev words cword\n")
	b.WriteString("    _init_completion || return\n")
	b.WriteString("\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	b.WriteString("\n")
	b.WriteString("    # Complete providers after --provider\n")
	b.WriteString("    case \"$prev\" in\n")
	b.WriteString("        --provider)\n")
	b.WriteString(fmt.Sprintf("            COMPREPLY=($(compgen -W \"%s\" -- \"$cur\"))\n", providers))
	b.WriteString("            return 0\n")
	b.WriteString("            ;;\n")
	b.WriteString("        --model|-m)\n")
	b.WriteString(fmt.Sprintf("            COMPREPLY=($(compgen -W \"%s\" -- \"$cur\"))\n", strings.Join(g.Models, " ")))
	b.WriteString("            return 0\n")
	b.WriteString("            ;;\n")
	b.WriteString("        --output-format|-o)\n")
	b.WriteString("            COMPREPLY=($(compgen -W \"text json stream-json\" -- \"$cur\"))\n")
	b.WriteString("            return 0\n")
	b.WriteString("            ;;\n")
	b.WriteString("        --input-format)\n")
	b.WriteString("            COMPREPLY=($(compgen -W \"text stream-json\" -- \"$cur\"))\n")
	b.WriteString("            return 0\n")
	b.WriteString("            ;;\n")
	b.WriteString("        --system-prompt-file|--append-system-prompt-file|--settings)\n")
	b.WriteString("            COMPREPLY=($(compgen -f -- \"$cur\"))\n")
	b.WriteString("            return 0\n")
	b.WriteString("            ;;\n")
	b.WriteString("        --add-dir|--cwd)\n")
	b.WriteString("            COMPREPLY=($(compgen -d -- \"$cur\"))\n")
	b.WriteString("            return 0\n")
	b.WriteString("            ;;\n")
	b.WriteString("    esac\n")
	b.WriteString("\n")
	b.WriteString("    # Complete slash commands when input starts with /\n")
	b.WriteString("    if [[ \"$cur\" == /* ]]; then\n")
	b.WriteString(fmt.Sprintf("        COMPREPLY=($(compgen -W \"%s\" -- \"$cur\"))\n", slashCmds))
	b.WriteString("        return 0\n")
	b.WriteString("    fi\n")
	b.WriteString("\n")
	b.WriteString("    # Complete flags when input starts with -\n")
	b.WriteString("    if [[ \"$cur\" == -* ]]; then\n")
	b.WriteString(fmt.Sprintf("        COMPREPLY=($(compgen -W \"%s\" -- \"$cur\"))\n", strings.Join(flags, " ")))
	b.WriteString("        return 0\n")
	b.WriteString("    fi\n")
	b.WriteString("\n")
	b.WriteString("    # Complete subcommands after rho\n")
	b.WriteString("    if [[ ${COMP_CWORD} -eq 1 ]]; then\n")
	b.WriteString(fmt.Sprintf("        COMPREPLY=($(compgen -W \"%s\" -- \"$cur\"))\n", strings.Join(subcommands, " ")))
	b.WriteString("        return 0\n")
	b.WriteString("    fi\n")
	b.WriteString("\n")

	// Subcommand-specific completions
	b.WriteString("    # Subcommand-specific completions\n")
	b.WriteString("    local subcmd=\"${COMP_WORDS[1]}\"\n")
	b.WriteString("    case \"$subcmd\" in\n")
	for _, cmd := range g.Commands {
		if len(cmd.Subcommands) > 0 {
			subs := make([]string, 0, len(cmd.Subcommands))
			for _, sc := range cmd.Subcommands {
				subs = append(subs, sc.Name)
			}
			b.WriteString(fmt.Sprintf("        %s)\n", cmd.Name))
			b.WriteString(fmt.Sprintf("            COMPREPLY=($(compgen -W \"%s\" -- \"$cur\"))\n", strings.Join(subs, " ")))
			b.WriteString("            return 0\n")
			b.WriteString("            ;;\n")
		}
	}
	b.WriteString("    esac\n")
	b.WriteString("\n")
	b.WriteString("    return 0\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("complete -F _rho_completions rho\n")

	return b.String()
}

// GenerateZsh returns a complete zsh completion script for rho.
func (g *CompletionGenerator) GenerateZsh() string {
	var b strings.Builder

	b.WriteString("#compdef rho\n")
	b.WriteString("# zsh completion for rho\n")
	b.WriteString("# Auto-generated by rho completions generator\n\n")

	b.WriteString("_rho() {\n")
	b.WriteString("    local -a commands\n")
	b.WriteString("    local -a global_flags\n")
	b.WriteString("\n")

	// Commands array
	b.WriteString("    commands=(\n")
	for _, cmd := range g.Commands {
		b.WriteString(fmt.Sprintf("        '%s:%s'\n", cmd.Name, escapeZsh(cmd.Description)))
	}
	b.WriteString("    )\n\n")

	// Global flags via _arguments
	b.WriteString("    _arguments -C \\\n")
	for i, f := range g.Flags {
		suffix := " \\"
		if i == len(g.Flags)-1 {
			suffix = ""
		}
		if f.Type == "bool" {
			if f.Short != "" {
				b.WriteString(fmt.Sprintf("        '(-%s --%s)'{-%s,--%s}'[%s]'%s\n", f.Short, f.Name, f.Short, f.Name, escapeZsh(f.Description), suffix))
			} else {
				b.WriteString(fmt.Sprintf("        '--%s[%s]'%s\n", f.Name, escapeZsh(f.Description), suffix))
			}
		} else {
			choices := ""
			if len(f.Choices) > 0 {
				choices = "(" + strings.Join(f.Choices, " ") + ")"
			}
			if f.Short != "" {
				b.WriteString(fmt.Sprintf("        '(-%s --%s)'{-%s,--%s}'[%s]:%s:%s'%s\n", f.Short, f.Name, f.Short, f.Name, escapeZsh(f.Description), f.Name, choices, suffix))
			} else {
				b.WriteString(fmt.Sprintf("        '--%s[%s]:%s:%s'%s\n", f.Name, escapeZsh(f.Description), f.Name, choices, suffix))
			}
		}
	}
	b.WriteString("        '1:command:->commands' \\\n")
	b.WriteString("        '*::arg:->args'\n")
	b.WriteString("\n")

	b.WriteString("    case $state in\n")
	b.WriteString("        commands)\n")
	b.WriteString("            _describe -t commands 'rho commands' commands\n")
	b.WriteString("            ;;\n")
	b.WriteString("        args)\n")
	b.WriteString("            case $words[1] in\n")
	for _, cmd := range g.Commands {
		if len(cmd.Subcommands) > 0 {
			b.WriteString(fmt.Sprintf("                %s)\n", cmd.Name))
			b.WriteString("                    local -a subcmds\n")
			b.WriteString("                    subcmds=(\n")
			for _, sc := range cmd.Subcommands {
				b.WriteString(fmt.Sprintf("                        '%s:%s'\n", sc.Name, escapeZsh(sc.Description)))
			}
			b.WriteString("                    )\n")
			b.WriteString("                    _describe -t commands 'subcommands' subcmds\n")
			b.WriteString("                    ;;\n")
		}
	}
	b.WriteString("            esac\n")
	b.WriteString("            ;;\n")
	b.WriteString("    esac\n")
	b.WriteString("}\n\n")

	// Slash commands completion function
	b.WriteString("_rho_slash_commands() {\n")
	b.WriteString("    local -a slash_commands\n")
	b.WriteString("    slash_commands=(\n")
	for _, sc := range g.SlashCommands {
		b.WriteString(fmt.Sprintf("        '%s'\n", sc))
	}
	b.WriteString("    )\n")
	b.WriteString("    compadd -a slash_commands\n")
	b.WriteString("}\n\n")

	// Provider completion function
	b.WriteString("_rho_providers() {\n")
	b.WriteString("    local -a providers\n")
	b.WriteString("    providers=(\n")
	for _, p := range g.Providers {
		b.WriteString(fmt.Sprintf("        '%s'\n", p))
	}
	b.WriteString("    )\n")
	b.WriteString("    compadd -a providers\n")
	b.WriteString("}\n\n")

	b.WriteString("_rho \"$@\"\n")

	return b.String()
}

// GenerateFish returns a complete fish shell completion script for rho.
func (g *CompletionGenerator) GenerateFish() string {
	var b strings.Builder

	b.WriteString("# fish completion for rho\n")
	b.WriteString("# Auto-generated by rho completions generator\n\n")

	// Disable file completions by default
	b.WriteString("complete -c rho -f\n\n")

	// Subcommands
	b.WriteString("# Subcommands\n")
	for _, cmd := range g.Commands {
		b.WriteString(fmt.Sprintf("complete -c rho -n '__fish_use_subcommand' -a '%s' -d '%s'\n",
			cmd.Name, escapeFish(cmd.Description)))
	}
	b.WriteString("\n")

	// Subcommand-specific completions
	for _, cmd := range g.Commands {
		if len(cmd.Subcommands) > 0 {
			b.WriteString(fmt.Sprintf("# %s subcommands\n", cmd.Name))
			for _, sc := range cmd.Subcommands {
				b.WriteString(fmt.Sprintf("complete -c rho -n '__fish_seen_subcommand_from %s' -a '%s' -d '%s'\n",
					cmd.Name, sc.Name, escapeFish(sc.Description)))
			}
			b.WriteString("\n")
		}
		// Command-specific flags
		if len(cmd.Flags) > 0 {
			b.WriteString(fmt.Sprintf("# %s flags\n", cmd.Name))
			for _, f := range cmd.Flags {
				if f.Short != "" {
					b.WriteString(fmt.Sprintf("complete -c rho -n '__fish_seen_subcommand_from %s' -l '%s' -s '%s' -d '%s'",
						cmd.Name, f.Name, f.Short, escapeFish(f.Description)))
				} else {
					b.WriteString(fmt.Sprintf("complete -c rho -n '__fish_seen_subcommand_from %s' -l '%s' -d '%s'",
						cmd.Name, f.Name, escapeFish(f.Description)))
				}
				if f.Type == "bool" {
					// no argument required
				} else {
					b.WriteString(" -r")
					if len(f.Choices) > 0 {
						b.WriteString(fmt.Sprintf(" -a '%s'", strings.Join(f.Choices, " ")))
					}
				}
				b.WriteString("\n")
			}
			b.WriteString("\n")
		}
	}

	// Global flags
	b.WriteString("# Global flags\n")
	for _, f := range g.Flags {
		if f.Short != "" {
			b.WriteString(fmt.Sprintf("complete -c rho -l '%s' -s '%s' -d '%s'",
				f.Name, f.Short, escapeFish(f.Description)))
		} else {
			b.WriteString(fmt.Sprintf("complete -c rho -l '%s' -d '%s'",
				f.Name, escapeFish(f.Description)))
		}
		if f.Type == "bool" {
			// no argument required
		} else {
			b.WriteString(" -r")
			if len(f.Choices) > 0 {
				b.WriteString(fmt.Sprintf(" -a '%s'", strings.Join(f.Choices, " ")))
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")

	// Provider completions for --provider
	b.WriteString("# Provider completions\n")
	b.WriteString(fmt.Sprintf("complete -c rho -l 'provider' -r -a '%s' -d 'LLM provider'\n",
		strings.Join(g.Providers, " ")))
	b.WriteString("\n")

	// Slash commands
	b.WriteString("# Slash commands (for interactive mode reference)\n")
	for _, sc := range g.SlashCommands {
		b.WriteString(fmt.Sprintf("complete -c rho -a '%s' -d 'Slash command'\n", sc))
	}

	return b.String()
}

// GenerateJSON returns a machine-readable JSON completion spec for IDE integration.
func (g *CompletionGenerator) GenerateJSON() (string, error) {
	v := strings.TrimSpace(version)
	if v == "" {
		v = "dev"
	}
	spec := struct {
		Name          string        `json:"name"`
		Version       string        `json:"version"`
		Commands      []CommandInfo `json:"commands"`
		GlobalFlags   []FlagInfo    `json:"global_flags"`
		SlashCommands []string      `json:"slash_commands"`
		Providers     []string      `json:"providers"`
		Models        []string      `json:"models"`
	}{
		Name:          "rho",
		Version:       v,
		Commands:      g.Commands,
		GlobalFlags:   g.Flags,
		SlashCommands: g.SlashCommands,
		Providers:     g.Providers,
		Models:        g.Models,
	}

	data, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to marshal completion JSON: %w", err)
	}
	return string(data), nil
}

func commandInfosFromCobra(cmds []*cobra.Command) []CommandInfo {
	infos := make([]CommandInfo, 0, len(cmds))
	for _, cmd := range cmds {
		if cmd.Hidden {
			continue
		}
		info := CommandInfo{
			Name:        cmd.Name(),
			Description: strings.TrimSpace(cmd.Short),
			Flags:       flagsFromFlagSet(cmd.NonInheritedFlags()),
		}
		info.Subcommands = commandInfosFromCobra(cmd.Commands())
		infos = append(infos, info)
	}
	return infos
}

func augmentCommandInfos(commands []CommandInfo) {
	for i := range commands {
		switch commands[i].Name {
		case "completion":
			commands[i].Subcommands = []CommandInfo{
				{Name: "bash", Description: "Generate bash completion"},
				{Name: "zsh", Description: "Generate zsh completion"},
				{Name: "fish", Description: "Generate fish completion"},
				{Name: "powershell", Description: "Generate PowerShell completion"},
				{Name: "json", Description: "Generate machine-readable completion metadata"},
			}
		case "config":
			commands[i].Subcommands = []CommandInfo{
				{Name: "get", Description: "Get a setting value"},
				{Name: "set", Description: "Set a setting value"},
				{Name: "provider", Description: "Set the LLM provider"},
				{Name: "model", Description: "Set the model"},
				{Name: "keys", Description: "Show API key configuration"},
				{Name: "routing-preview", Description: "Show routing JSON for a model"},
				{Name: "migrate-deployments", Description: "Upgrade legacy provider config to deployments v2"},
			}
		}
		if len(commands[i].Subcommands) > 0 {
			augmentCommandInfos(commands[i].Subcommands)
		}
	}
}

func flagsFromFlagSet(fs *pflag.FlagSet) []FlagInfo {
	if fs == nil {
		return nil
	}
	var flags []FlagInfo
	fs.VisitAll(func(f *pflag.Flag) {
		if f == nil || f.Name == "help" {
			return
		}
		flags = append(flags, FlagInfo{
			Name:        f.Name,
			Short:       f.Shorthand,
			Description: f.Usage,
			Type:        normalizeFlagType(f.Value.Type()),
			Choices:     flagChoices(f.Name),
		})
	})
	sort.SliceStable(flags, func(i, j int) bool {
		return flags[i].Name < flags[j].Name
	})
	return flags
}

func normalizeFlagType(flagType string) string {
	switch flagType {
	case "bool":
		return "bool"
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64":
		return "int"
	default:
		return "string"
	}
}

func flagChoices(name string) []string {
	switch name {
	case "output-format":
		return []string{"text", "json", "stream-json"}
	case "input-format":
		return []string{"text", "stream-json"}
	case "direction":
		return []string{"lower", "higher"}
	case "auto":
		return []string{"supervised", "basic", "semi", "full", "yolo"}
	default:
		return nil
	}
}

// InstallCompletion returns the filesystem path where the completion script
// should be installed for the given shell. It does not write the file; the
// caller should decide whether to proceed.
func InstallCompletion(shell string) (string, error) {
	switch shell {
	case "bash":
		return bashInstallPath(), nil
	case "zsh":
		return zshInstallPath(), nil
	case "fish":
		return fishInstallPath(), nil
	default:
		return "", fmt.Errorf("unsupported shell: %s (supported: bash, zsh, fish)", shell)
	}
}

func bashInstallPath() string {
	// Prefer user-local path
	home, err := os.UserHomeDir()
	if err != nil {
		return "/etc/bash_completion.d/rho"
	}
	localDir := filepath.Join(home, ".local", "share", "bash-completion", "completions")
	if info, err := os.Stat(localDir); err == nil && info.IsDir() {
		return filepath.Join(localDir, "rho")
	}
	// On macOS, use homebrew path if available.
	// ARM Macs (M1+) install Homebrew to /opt/homebrew; Intel Macs use /usr/local.
	if runtime.GOOS == "darwin" {
		for _, prefix := range []string{"/opt/homebrew", "/usr/local"} {
			brewDir := filepath.Join(prefix, "etc", "bash_completion.d")
			if info, err := os.Stat(brewDir); err == nil && info.IsDir() {
				return filepath.Join(brewDir, "rho")
			}
		}
	}
	// Fallback: try system-wide
	sysDir := "/etc/bash_completion.d"
	if info, err := os.Stat(sysDir); err == nil && info.IsDir() {
		return filepath.Join(sysDir, "rho")
	}
	// Final fallback: user-local
	return filepath.Join(home, ".local", "share", "bash-completion", "completions", "rho")
}

func zshInstallPath() string {
	// Check $fpath from environment
	fpath := os.Getenv("FPATH")
	if fpath != "" {
		parts := strings.Split(fpath, ":")
		for _, p := range parts {
			if p != "" {
				if info, err := os.Stat(p); err == nil && info.IsDir() { // #nosec G703 -- shell completion only probes the user-selected directory
					return filepath.Join(p, "_rho")
				}
			}
		}
		// Use first entry even if it doesn't exist yet
		if parts[0] != "" {
			return filepath.Join(parts[0], "_rho")
		}
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "/usr/local/share/zsh/site-functions/_rho"
	}
	return filepath.Join(home, ".zsh", "completions", "_rho")
}

func fishInstallPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(os.TempDir(), "rho.fish")
	}
	return filepath.Join(home, ".config", "fish", "completions", "rho.fish")
}

// escapeZsh escapes single quotes for zsh completion descriptions.
func escapeZsh(s string) string {
	return strings.ReplaceAll(s, "'", "'\\''")
}

// escapeFish escapes single quotes for fish completion descriptions.
func escapeFish(s string) string {
	return strings.ReplaceAll(s, "'", "\\'")
}
