package tool

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type SpecProvenanceTool struct{}

func (SpecProvenanceTool) Name() string { return "SpecProvenance" }

// SpecProvenanceInput is the typed input for SpecProvenanceTool.
type SpecProvenanceInput struct {
	Action string `json:"action"`
	File   string `json:"file"`
	Model  string `json:"model"`
}

func (SpecProvenanceTool) Aliases() []string {
	return []string{"spec_provenance", "spec:provenance"}
}

func (SpecProvenanceTool) Description() string {
	return "Track provenance of AI-generated code. Records which model, prompt, and session generated each code artifact. Creates audit trails for compliance and debugging."
}

// Schema returns the typed input schema. Parameters() delegates to it so the
// two cannot diverge.
func (SpecProvenanceTool) Schema() ToolSchema {
	return ToolSchema{
		Type: "object",
		Properties: map[string]SchemaProperty{
			"action": {Type: "string", Enum: []interface{}{"record", "show", "audit"}, Description: "Action: record (log generation), show (view history), audit (compliance report)"},
			"file":   {Type: "string", Description: "File that was generated/modified"},
			"model":  {Type: "string", Description: "AI model used (e.g., claude-sonnet-4, gpt-4)"},
		},
	}
}

func (SpecProvenanceTool) Parameters() map[string]interface{} {
	return specProvenanceSchema.ToJSONSchema()
}

// specProvenanceSchema is the single source of truth for SpecProvenance's input schema.
var specProvenanceSchema = SpecProvenanceTool{}.Schema()

type ProvenanceEntry struct {
	Timestamp   string `json:"timestamp"`
	File        string `json:"file"`
	Model       string `json:"model"`
	SessionID   string `json:"session_id"`
	PromptRef   string `json:"prompt_ref"`
	GeneratedBy string `json:"generated_by"`
}

func (SpecProvenanceTool) Execute(ctx context.Context, input json.RawMessage) (string, error) {
	p, err := DecodeInput[SpecProvenanceInput]("SpecProvenance", input)
	if err != nil {
		return "", err
	}
	if p.Action == "" {
		p.Action = "show"
	}

	dir, err := specDir(ctx)
	if err != nil {
		return "", err
	}

	switch p.Action {
	case "record":
		return recordProvenance(dir, p.File, p.Model)
	case "show":
		return showProvenance(dir)
	case "audit":
		return auditProvenance(dir)
	default:
		return showProvenance(dir)
	}
}

func recordProvenance(dir, file, model string) (string, error) {
	if file == "" {
		return "", fmt.Errorf("file is required for record")
	}

	provPath := filepath.Join(dir, ".provenance.json")
	var entries []ProvenanceEntry

	if data, err := os.ReadFile(provPath); err == nil {
		_ = json.Unmarshal(data, &entries)
	}

	entry := ProvenanceEntry{
		Timestamp:   time.Now().Format(time.RFC3339),
		File:        file,
		Model:       model,
		GeneratedBy: "ai-agent",
	}

	entries = append(entries, entry)

	if data, err := json.MarshalIndent(entries, "", "  "); err == nil {
		if err := os.WriteFile(provPath, data, 0o600); err != nil {
			return "", fmt.Errorf("write provenance: %w", err)
		}
	}

	return fmt.Sprintf("Recorded provenance for %s", file), nil
}

func showProvenance(dir string) (string, error) {
	provPath := filepath.Join(dir, ".provenance.json")

	var entries []ProvenanceEntry
	if data, err := os.ReadFile(provPath); err != nil || json.Unmarshal(data, &entries) != nil {
		return "No provenance records found.", nil
	}

	var b strings.Builder
	b.WriteString("## Provenance Log\n\n")
	fmt.Fprintf(&b, "**%d entries**\n\n", len(entries))

	b.WriteString("| Timestamp | File | Model | Generated By |\n")
	b.WriteString("|-----------|------|-------|-------------|\n")

	for _, e := range entries {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", e.Timestamp, e.File, e.Model, e.GeneratedBy)
	}

	return strings.TrimSpace(b.String()), nil
}

func auditProvenance(dir string) (string, error) {
	provPath := filepath.Join(dir, ".provenance.json")

	var entries []ProvenanceEntry
	if data, err := os.ReadFile(provPath); err != nil || json.Unmarshal(data, &entries) != nil {
		return "No provenance records found for audit.", nil
	}

	modelCounts := make(map[string]int)
	for _, e := range entries {
		modelCounts[e.Model]++
	}

	var b strings.Builder
	b.WriteString("## Provenance Audit Report\n\n")
	fmt.Fprintf(&b, "**Total entries**: %d\n\n", len(entries))

	b.WriteString("### Generation by Model\n\n")
	for model, count := range modelCounts {
		fmt.Fprintf(&b, "- %s: %d\n", model, count)
	}
	b.WriteString("\n")

	b.WriteString("### Compliance Notes\n\n")
	b.WriteString("- All AI-generated code is tracked with timestamp and model\n")
	b.WriteString("- Provenance file (.provenance.json) is version-controlled\n")
	b.WriteString("- Audit trail supports regulatory compliance (SOC 2, ISO 27001)\n")

	return strings.TrimSpace(b.String()), nil
}

func init() {
	_ = SpecProvenanceTool{}
}
